import os

BROKER_ADDRESS = os.getenv("BROKER_ADDRESS", "localhost")
MQTT_PORT = int(os.getenv("MQTT_PORT", "1883"))
MQTT_BASE_TOPIC = "bins"
MQTT_QOS = 0
N_BINS = 5
COLLECT_THRESHOLD = 95
DISCRETIZATION = 10
MAX_FILL = 100
COLLECTION_COST = 1
OVERFLOW_PENALTY = 5
MAX_INCREMENT = 5
GAMMA = 0.95
SLEEP_TIME = 1
FILL_STEPS = 10